### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by k11mamaes** [christocracy/cordova-plugin-background-geolocation#175]
There seems to be a problem with the cordova-plugin-geolocation dependency.
I tried reinstalling the plugin and building the sample app and received the following error message:

SampleApp rm -rf platforms/android
SampleApp rm -rf plugins/org.transistorsoft.cordova.background-geolocation
SampleApp rm plugins/android.json
SampleApp cordova plugin add https://github.com/christocracy/cordova-plugin-background-geolocation.git
Fetching plugin "https://github.com/christocracy/cordova-plugin-background-geolocation.git" via git clone
SampleApp cordova platform add android
Creating android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.transistorsoft.backgroundgeolocation
	Name: Cordova Background GeoLocation
	Android target: android-19
Copying template files...
Project successfully created.
Installing "org.apache.cordova.dialogs" for android
Installing "org.apache.cordova.geolocation" for android
Installing "org.transistorsoft.cordova.background-geolocation" for android
Fetching plugin "cordova-plugin-geolocation" via plugin registry
Failed to install 'org.transistorsoft.cordova.background-geolocation':Error: 404 Not Found: cordova-plugin-geolocation
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:14)
    at Request._callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:236:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1142:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1096:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:938:16
    at process._tickCallback (node.js:419:13)
Error: 404 Not Found: cordova-plugin-geolocation
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:14)
    at Request._callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:236:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1142:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1096:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:938:16
    at process._tickCallback (node.js:419:13)

**Comment by christocracy** [comment]
What version of Cordova are you using?

It probably has something to do with the PR I accepted
https://github.com/christocracy/cordova-plugin-background-geolocation/pull/173

**Comment by k11mamaes** [comment]
ah i see.  im running cordova 4.2.0

**Comment by piavgh** [comment]
Hi @christocracy 

Today I tried to add this repo into my project, and I got the same error with topic owner.
My cordova version is 4.3.0

Hope you fix this soon

**Comment by christocracy** [comment]
It seems I naively accepted a pull request upgrading the dependencies to
new Cordova 5 npm style.  If you upgrade to Cordova 5, it'll work

On Wednesday, May 6, 2015, Hoang Trinh Huy <notifications@github.com> wrote:

> Hi @christocracy <https://github.com/christocracy>
>
> Today I tried to add this repo into my project, and I got the same error
> with topic owner.
> My cordova version is 4.3.0
>
> Hope you fix this soon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/175#issuecomment-99701857>
> .
>


-- 
Snet from Gmail Mobile

**Comment by piavgh** [comment]
Thank you @christocracy 
My problem solved.

**Comment by piavgh** [comment]
Hi @christocracy 

I have one more question, if I still want to use this repo with cordova 4.3.0, what I have to do?

Because I've just realized that cordova 5.0 break my existing code, and now I don't have enough time to fix every error

Thank you very much

**Comment by christocracy** [comment]
I've tagged the version before implementing the new Cordova 5-style ```<dependency />```

Simply install the plugin by appending ```#cordova-4.x``` to the plugin url:

``` 
cordova plugin add cordova plugin add https://github.com/christocracy/cordova-plugin-background-geolocation.git#cordova-4.x
```

FYI:  Cordova 5 has [migrated to npm](https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html) for plugin-hosting, changing the naming convention of cordova plugins:

OLD (pre Cordova 5):  ```org.apache.cordova.geolocation```
NEW (Cordova 5+):  ```cordova-plugin-geolocation```

Since my plugin has 2 dependencies, the tag-branch ```#cordova-4.x``` uses this format:
```
<dependency id="org.apache.cordova.geolocation" />
 <dependency id="org.apache.cordova.dialogs" />
```

And #master branch uses new Cordova 5 style:
```
<dependency id="cordova-plugin-geolocation" />
<dependency id="cordova-plugin-dialogs" />
```
