### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [christocracy/cordova-plugin-background-geolocation#190]
Kimberlees-Mini:LinemansApp kimberleearmstrong$ cordova plugin add https://github.com/christocracy/cordova-plugin-background-geolocation.git
Fetching plugin "https://github.com/christocracy/cordova-plugin-background-geolocation.git" via git clone
Installing "org.transistorsoft.cordova.background-geolocation" for android
Fetching plugin "cordova-plugin-geolocation" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-geolocation
npm http 404 http://registry.cordova.io/cordova-plugin-geolocation
Failed to install 'org.transistorsoft.cordova.background-geolocation':Error: 404 Not Found: cordova-plugin-geolocation
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
Error: 404 Not Found: cordova-plugin-geolocation
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
Kimberlees-Mini:LinemansApp kimberleearmstrong$

**Comment by christocracy** [comment]
The plugin dependencies were upgraded to new npm style for Cordova 5

On Wednesday, May 27, 2015, KimberleeDArmstrong <notifications@github.com>
wrote:

> Closed #190
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/190>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/190#event-315406411>
> .
>


-- 
Snet from Gmail Mobile
